import './theme-toggle.js';
import './site-menu.js';
import './catalog-slider.js';
import './blur.js';
import './product.js';
import './call-btn.js';
import './response.js';
import './feedback.js';
import './decor.js';
